import fs from "node:fs";
import path from "node:path";
import { AnalysisResult, TypeRef, ComponentDesc } from "./analyzer.js";
import { ensureDirSync, capitalize } from "./utils.js";

export function emitReactIntrinsicDts(
    analysis: AnalysisResult,
    outDir: string,
    outFile: string,
    opts: { addReactHtmlAttributes: boolean }
) {
    ensureDirSync(fs, outDir);

    let out = `/* Auto-generated by crie. Do not edit manually. */\n\n`;

    // Namespaced type exports
    for (const [fileId, map] of analysis.namespaces) {
        out += `declare namespace AloTypes$${fileId} {\n`;
        for (const [exportName, decl] of map) {
            out += indent(1) + sanitizeDeclaration(decl) + "\n";
        }
        out += `}\n\n`;
    }

    // JSX IntrinsicElements
    out += `export {};\n`;
    out += `declare global {\n`;
    out += indent(1) + `namespace React {\n`;
    out += indent(2) + `namespace JSX {\n`;
    out += indent(3) + `interface IntrinsicElements {\n`;

    for (const comp of analysis.components) {
        out += emitComponentEntry(comp);
    }

    out += indent(3) + `}\n`;
    out += indent(2) + `}\n`;
    out += indent(1) + `}\n`;
    out += `}\n`;

    const outPath = path.join(outDir, outFile);
    fs.writeFileSync(outPath, out, "utf8");
    return outPath;
}

function emitComponentEntry(c: ComponentDesc): string {
    const lines: string[] = [];

    for (const input of c.inputs) {
        const name = quoteIfNeeded(input.name);
        const optional = input.optional ? "?" : "";
        lines.push(`${indent(5)}${name}${optional}: ${printTypeRef(input.type)};`);
    }

    for (const output of c.outputs) {
        const handler = `on${capitalize(output.name)}`;
        lines.push(`${indent(5)}${quoteIfNeeded(handler)}?: (e: CustomEvent<${printTypeRef(output.payload)}>) => void;`);
    }

    lines.push(`${indent(5)}children?: unknown;`);

    return `${indent(4)}'${c.tag}': {\n${lines.join("\n")}\n${indent(4)}};\n`;
}

function printTypeRef(t: TypeRef): string {
    if (t.kind === "inline") return t.text;
    return "any";
}

function quoteIfNeeded(name: string): string {
    return /^[a-zA-Z_]\w*$/.test(name) ? name : `'${name}'`;
}

function indent(n: number): string {
    return "  ".repeat(n);
}

function sanitizeDeclaration(decl: string): string {
    return decl.replace(/^declare\s+/, "");
}
