import fs from "node:fs";
import path from "node:path";
import { AnalysisResult, TypeRef, ComponentDesc } from "./analyzer.js";
import { ensureDirSync, capitalize } from "./utils.js";

export function emitReactIntrinsicDts(
    analysis: AnalysisResult,
    outDir: string,
    outFile: string,
    opts: { addReactHtmlAttributes: boolean }
) {
    ensureDirSync(fs, outDir);

    let out = `/* Auto-generated by crie. Do not edit by hand. */\n\n`;

    // Emit namespaces for referenced types (file-scoped)
    for (const [fileId, map] of analysis.namespaces) {
        out += `declare namespace AloTypes$${fileId} {\n`;
        for (const [exportName, decl] of map) {
            out += indent(1) + sanitizeDeclaration(decl) + "\n";
        }
        out += `}\n\n`;
    }

    // Emit JSX augmentation
    out += `export {};\n`;
    out += `declare global {\n`;
    out += indent(1) + `namespace React {\n`;
    out += indent(2) + `namespace JSX {\n`;
    out += indent(3) + `interface IntrinsicElements {\n`;

    for (const comp of analysis.components) {
        out += emitComponentEntry(comp, opts);
    }

    out += indent(3) + `}\n`;
    out += indent(2) + `}\n`;
    out += indent(1) + `}\n`;
    out += `}\n`;

    const outPath = path.join(outDir, outFile);
    fs.writeFileSync(outPath, out, "utf8");
    return outPath;
}

function emitComponentEntry(c: ComponentDesc, opts: { addReactHtmlAttributes: boolean }): string {
    let s = "";
    s += indent(4) + `'${c.tag}': `;
    const parts: string[] = [];

    if (opts.addReactHtmlAttributes) {
        parts.push(`React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement>`);
    } else {
        parts.push(`{}`);
    }

    // Inputs
    const inputLines = c.inputs.map(p => `${quoteIfNeeded(p.name)}?: ${printTypeRef(p.type)};`);
    if (inputLines.length) parts.push(`{\n${indent(6)}${inputLines.join(`\n${indent(6)}`)}\n${indent(5)}}`);

    // Events (as onX callbacks with CustomEvent payload)
    const eventLines = c.outputs.map(o => {
        const handler = `on${capitalize(o.name)}`;
        return `${quoteIfNeeded(handler)}?: (e: CustomEvent<${printTypeRef(o.payload)}>) => void;`;
    });
    if (eventLines.length) parts.push(`{\n${indent(6)}${eventLines.join(`\n${indent(6)}`)}\n${indent(5)}}`);

    // children
    parts.push(`{ children?: React.ReactNode }`);

    s += parts.join(" & ") + ";\n";
    return s;
}

function printTypeRef(t: TypeRef): string {
    if (t.kind === "inline") return t.text;
    return `AloTypes$${t.fileId}.${t.exportName}`;
}

function quoteIfNeeded(name: string) {
    // keep kebab props as quoted keys
    return /^[a-zA-Z_]\w*$/.test(name) ? name : `'${name}'`;
}

function indent(n: number) {
    return "  ".repeat(n);
}

function sanitizeDeclaration(decl: string): string {
    // Remove leading "declare " if present and ensure it's an exportable type/interface/enum
    return decl.replace(/^declare\s+/, "");
}
