import fs from "node:fs";
import path from "node:path";
import { AnalysisResult, TypeRef, ComponentDesc } from "./analyzer.js";
import { ensureDirSync, capitalize } from "./utils.js";

export function emitReactIntrinsicDts(
    analysis: AnalysisResult,
    outDir: string,
    outFile: string,
    opts: { addReactHtmlAttributes: boolean }
) {
    ensureDirSync(fs, outDir);

    let out = `/* Auto-generated by crie. Do not edit manually. */\n\n`;

    // Namespaced type exports
    for (const [fileId, map] of analysis.namespaces) {
        out += `declare namespace AloTypes$${fileId} {\n`;
        for (const [exportName, decl] of map) {
            out += indent(1) + sanitizeDeclaration(decl) + "\n";
        }
        out += `}\n\n`;
    }

    // JSX IntrinsicElements
    out += `export {};\n`;
    out += `declare global {\n`;
    out += indent(1) + `namespace React {\n`;
    out += indent(2) + `namespace JSX {\n`;
    out += indent(3) + `interface IntrinsicElements {\n`;

    for (const comp of analysis.components) {
        out += emitComponentEntry(comp, opts);
    }

    out += indent(3) + `}\n`;
    out += indent(2) + `}\n`;
    out += indent(1) + `}\n`;
    out += `}\n`;

    const outPath = path.join(outDir, outFile);
    fs.writeFileSync(outPath, out, "utf8");
    return outPath;
}

function emitComponentEntry(c: ComponentDesc, _opts: { addReactHtmlAttributes: boolean }): string {
    let s = "";
    s += indent(4) + `'${c.tag}': `;
    const lines: string[] = [];

    for (const input of c.inputs) {
        const optional = input.optional ? "?" : "";
        lines.push(`${quoteIfNeeded(input.name)}${optional}: ${printTypeRef(input.type)};`);
    }

    for (const output of c.outputs) {
        const handler = `on${capitalize(output.name)}`;
        lines.push(`${quoteIfNeeded(handler)}?: (e: CustomEvent<${printTypeRef(output.payload)}>) => void;`);
    }

    lines.push(`children?: unknown;`);

    if (lines.length) {
        s += `{\n${indent(5)}${lines.join(`\n${indent(5)}`)}\n${indent(4)}};\n`;
    } else {
        s += `{ };\n`;
    }
    return s;
}

function printTypeRef(t: TypeRef): string {
    return t.kind === "inline" ? t.text : `AloTypes$${t.fileId}.${t.exportName}`;
}

function quoteIfNeeded(name: string): string {
    return /^[a-zA-Z_]\w*$/.test(name) ? name : `'${name}'`;
}

function indent(n: number): string {
    return "  ".repeat(n);
}

function sanitizeDeclaration(decl: string): string {
    return decl.replace(/^declare\s+/, "");
}
